README.md
- Added meeting info and some details
- We can continue to iterate (Used similar structure to SIG-Security)
- Please add reviewers as needed
=> Initial structure for README.md

README.md
Point to the right meeting minutes
=> Fixed the link to the meeting minutes

README.md
Congratulations @dfeddema! The TOC approved you as a co-chair.
@amye could we attach the voting record to this PR?
=> Update README.md with new co-chair Diane Feddema

recommendations/graduated/harbor.md
SIG-Runtime Graduation review request of Harbor as per https://github.com/cncf/toc/pull/311
=> Request for Harbor Graduation Review

recommendations/sandbox/metal3.md
Original link: https://bit.ly/metal3-sandbox-review
Fixes https://github.com/cncf/sig-runtime/issues/18
=> Moving Metal3 doc to Github

README.md
=> Update to from SIG to TAG

README.md
Fixing previous naming conventions that are still left in the document.
=> SIG->TAG updates

README.md
Voting results: https://lists.cncf.io/g/cncf-toc/message/6485
(also fixed a bit of table formatting).
=> Adding myself as tech lead

README.md
Signed-off-by: Klaus Ma <klaus@xflops.cn>
=> Update k82cn's info

README.md
Links to IoT Edge WG page from working group section of README.
=> Link to IoT Edge WG page from README

wg/bsi.md
CNCF Batch System Initiative Working Group proposal :)
fixed https://github.com/cncf/tag-runtime/issues/38
=> CNCF BSI WG Charter

wg/whitepapers/edge-native-application-principles.md
PR adds 
- cncf/tag-runtime/wg/whitepapers folder
- Draft of IoT Edge WG whitepaper Edge Native Application Principles
/cc @kate-goldenring
=> IoT Edge WG Whitepaper - Edge Native Application Principles

wg/whitepapers/edge-native-application-principles.md
Rephrases principle of "Aware of variable connectivity". 
Also, applies markdown linking (newlines, removes added spaces, etc)
cc @dejanb @cantbewong @joerober 
Signed-off-by: Kate Goldenring <kate.goldenring@fermyon.com>
=> Update white paper: use latest wording for principle of variable connectivity awareness

README.md
=> Add Heba and Nikhita to TAG Runtime members

website/content/_index.md
=> TAG-Runtime website fixes

README.md
=> Update README.md member list

README.md, website/content/_index.md
Ref: https://lists.cncf.io/g/cncf-toc/message/8005
cc @helayoty @raravena80
=> Add Heba as TAG Runtime co-chair

wg/wasm.md
Fixes #58 
Signed-off-by: Heba Elayoty <hebaelayoty@gmail.com>
=> Create Wasm wg

README.md
cc @raravena80 @helayoty  @nikhita
=> Add Rajas to TAG Runtime members

README.md
=> doc: Update README with the new TL and more

wg/sp-os.md
cc @raravena80 @helayoty @nikhita
=> Create Charter for Special Purpose Operating System Working Group

wg/sp-os.md
=> added link to the zoom meeting

README.md
Also fixes a few minor things and adds Sean McGinnis to list of members.
=> Add Special Purpose OS Working Group to list of WGs

README.md, website/layouts/_default/content.html, website/layouts/partials/feedback.html
=> Add feedback buttons to pages on the site

wg/cnaiwg
Resolves: https://github.com/cncf/toc/issues/1200
=> Create Cloud Native AI Working Group Charter

website/content/wgs/wasm.md
Update website content for WASM WG
=> Update wasm.md (website)

wg/whitepapers/edge-native-application-design-behaviors.md, wg/whitepapers/edge-native-application-principles.md
=> feat(whitepaper): add links to Edge Native Application Design Behaviors WP

website/config.toml, website/content/_index.md, website/content/blog/_index.md, website/content/search.md, website/content/wgs/COD/_index.md, website/content/wgs/COD/charter/_index.md, website/content/wgs/_index.md, website/content/wgs/bsi/_index.md, website/content/wgs/bsi/charter/_index.md, website/content/wgs/cnaiwg/_index.md, website/content/wgs/cnaiwg/charter/_index.md, website/content/wgs/iot/_index.md, website/content/wgs/iot/charter/_index.md, website/content/wgs/iot/whitepaper/edge-native-application-design-behaviors.md, website/content/wgs/iot/whitepaper/edge-native-application-principles.md, website/content/wgs/spos/_index.md, website/content/wgs/spos/charter/_index.md, website/content/wgs/wasm/_index.md, website/content/wgs/wasm/charter/_index.md
Some website updates
- Streamlined pages
- Preparing for the CN AI White Paper publication.
=> Website updates

website/config.toml, website/content/search.md, website/layouts/partials/sidebar-tree.html
=> Activated sidebar

README.md
Add missing email for rajas and fix the GitHub username
=> Add missing email for rajas

website/content/wgs/spos/charter/_index.md
adding youtube recordings link to Special Purpose OS Working Group
=> adding youtube recordings link sp-os-wg

website/content/blog/_index.md, website/content/blog/cnaiwg-kubecon-recap-03-31-24.md
- Creating a blog entry to be added on the tag-runtime website.
=> CNAI Kubecon EU Paris 2024 recap blog

website/content/blog/cnaiwg-kubecon-recap-03-31-24.md
This PR fixes missing formatting and adds a second author. to CNAI blog post.
=> fix typos and formatting and add second author

website/content/wgs/cnaiwg/_index.md, wgs/cnai/whitepapers/cnai/index.md
- Added a main page for C NAI WG
- Delete version info from the CN AI Whitepaper
=> More updates to the website

README.md
=> Update TOC liaisons

README.md
some links stopped working after deleting duplicated files: https://github.com/cncf/tag-runtime/pull/117
=> updating dead links

website/content/wgs/cnaiwg/_index.md, website/content/wgs/cnaiwg/glossary/index.md, website/content/wgs/cnaiwg/onboarding/index.md, wgs/cnai/charter/index.md, wgs/cnai/whitepapers/cloudnativeai.md
This PR adds:
- an onboarding section for new Joiners of the working group.
- a separate glossary page
=> Add glossary & onboarding section

website/content/wgs/cnaiwg/news/12_19_April_2024.md, website/content/wgs/cnaiwg/news/_index.md
This PR adds a section for news to encourage contribution and expose the rest of the community to the work the WG is doing.
=> add cnai news and the first post

website/content/wgs/cnaiwg/news/12_19_April_2024.md, website/content/wgs/cnaiwg/news/26_April_2024.md
=> Add News for 26 April 2024

website/content/wgs/wasm/deliverables, wgs/wasm/deliverables/index.md
Related to https://github.com/cncf/tag-runtime/pull/135
=> Add wasm wg deliverables folder

wgs/cnai/news/12_19_April_2024.md, wgs/cnai/news/29_April_03_May_2024.md
This Week in CN AI (03 May 2024)
=> This Week in CN AI (03 May 2024)

wgs/cnai/news/13_17_May_2024.md
=> add news this week

wgs/cnai/news/20_25_May_2024.md
=> news for the week

wgs/cnai/onboarding/index.md
update onboarding WG meeting wording
=> update onboarding WG meeting wording

wgs/cnai/news/05_10_May_2024.md, wgs/cnai/news/12_19_April_2024.md, wgs/cnai/news/13_17_May_2024.md, wgs/cnai/news/20_25_May_2024.md, wgs/cnai/news/26_April_2024.md, wgs/cnai/news/29_April_03_May_2024.md, wgs/cnai/news/July_latest_in_CNAI.md
=> Add latest in July news for CNAI

wgs/cnai/charter/index.md
Update times to match the real world times.
=> Update time/dates for meetings.

wgs/wasm/deliverables/wasm-oci-artifact/index.md
supported in https://github.com/bytecodealliance/componentize-dotnet/pull/32
@thomastaylor312
=> Move componentize-dotnet to implemented

wgs/bsi/charter/index.md
Primarily to fix the days of the meeting so that it reflects the meeting time on Mondays, not Thursdays.
But I thought I'd try and clean up some of the text while I was at it.
=> Fixing mistakes in the BSI charter

wgs/spos/charter/index.md
- Add myself as co-chair
- update the time of the meeting
- use simple link to community inviter
=> Update charter info

wgs/spos/charter/index.md
=> Revert "Update charter info"

website/content/en/blog/kubernetes-ai-5-talks-kubecon-india-12-06-24.md
* Add a blog to the tag-runtime website in the blog section.
Preview Link: https://deploy-preview-200--tag-runtime.netlify.app/blog/kubernetes-and-ai-5-talks-you-dont-want-to-miss-at-kubecon-india-2024/
=> 5 Talks You don't want to Miss at KubeCon India 2024 Blog

wgs/bsi/charter/index.md
One last place where I need to update the day-of-the-week change!
=> Fixing the day of the week for the Batch working group meeting
