README.md

The previous link was for 10AM U.S. Pacific, not 8AM.

Fix timezone converter link

---

wg/COD.md

- Renaud is now working on other topics and don't have anymore time for WG, thus marked as emeritus chair.
- Evan Lezar from NVIDIA is taking over Renaud's duty as co-chair.
- SIG->TAG naming update.

Update WG COD description

---

README.md
wg/bsi.md

Two additions:
* Adding a link to the batch working group on the tag-runtime README
* Adding the date and time and a meeting invite link to the bsi.md

Add link to Batch Working Group

---

README.md

This PR put [Karmada](https://karmada.io/) onto the project list as talked on [March 23rd, 2023](https://docs.google.com/document/d/1k7VNetgbuDNyIs_87GLQRH2W5SLgjgOhB6pDyv89MYk/edit#heading=h.4ud3fyz4qn3a) meeting.

Add Karmada project onto the project list

---

.github/settings.yml

Instead, this should be defined in https://github.com/cncf/people#configyaml-configures-cncf-org-repository-access
xref https://github.com/cncf/people/pull/251

.github: remove repo access control rules

---

wg/bsi.md

Mainly, this update is to fix the calendar invite link that apparently has been incorrect this entire time.
Additionally, I made a few tiny spelling corrections and moved MCAD in one place to a more appropriate part of the sentence.  Small stuff.

Fix meeting invite link

---

website/content/wgs/COD.md
website/content/wgs/_index.md
website/content/wgs/batch.md
website/content/wgs/iot.md
website/content/wgs/spos.md
website/content/wgs/wasm.md

This adds the charter and working group details to the published website.
Related: #61 
It is less than ideal at this point since it is duplicating the content from the `wg` folder in order to make it available for hugo rendering. The current tools like `readFile` from the docsy template does not allow pulling in files from outside the website directory.
Until we can find a workaround for that, this just copies the content. Once we find a better way, we should be able to keep the working group charters as the single source of truth and just pull it in to the rendered content. But for now, this makes a nice rendered view of our working groups to make it easier for folks to find and learn about the various working groups in TAG Runtime.

Add working group information to website

---

website/content/wgs/wasm.md
wg/wasm.md

We changed the meeting cadence of the WG Wasm meeting to fortnightly.
Links to calendar and google docs have been cleaned up.
/cc @endocrimes @devigned

Update WG Wasm meeting times

---

wg/wasm.md

In light of the work that Taylor Thomas has been leading the Wasm Working Group and his contributions to the broader community in Wasm and Kuberentes, we would like to add Taylor as a chair for the WG.

add Taylor Thomas as wg wasm chair

---

website/layouts/_default/baseof.html
website/layouts/blog/baseof.html
website/layouts/partials/gtm-noscript.html
website/layouts/partials/head.html

To allow us more flexibility we want to install GTM in place of just GA4. We will also be including a HubSpot tracking code using GTM. See https://github.com/cncf/cncf.io/issues/823

Installs GTM instead of just GA4

---

website/netlify.toml

To address [this issue](https://github.com/cncf/cncf.io/issues/824), we want to explicitly set `HUGO_ENV` so that it only is "production" on the production instance of the site. This is important so we don't run Google Analytics on preview or dev instances.

Try to explicitly set HUGO_ENV in netlify.toml

---

wgs/wasm/deliverables/wasm-oci-artifact.md
wgs/wasm/deliverables/wasm-oci-artifact/index.md

[wg-wasm](https://github.com/cncf/tag-runtime/blob/main/wgs/wasm/charter/index.md) has been working on defining a format for storing wasm workloads in an OCI format.  This adds the guidance as a deliverable for the working group.

Add wasm oci artifact guidance

---

website/layouts/partials/page-meta-links.html

The edit link was pointing to the wrong location for pages that are symlinked. The most immediate fix is here, to just remove it for these pages.

Remove edit link for pages that are symlinked

---

wgs/wasm/charter/index.md

This adds a few clarification points to the charter as requested by the TOC. Namely, this adds a list of some of the ongoing efforts of the WG as well as calling out the collaboration with other orgs like the ByteCode Alliance. It also removes Krustlet from the project list as it will be archived shortly

feat(wasm): Updates WG charter

---

website/content/en/wgs/cnaiwg/_index.md
website/content/ja/wgs/cnaiwg/_index.md

- Fix broken links in wgs/cnaiwg/_index.md (en/ja)
The links in https://tag-runtime.cncf.io/wgs/cnaiwg/#links are broken.

Fix broken links in wgs/cnaiwg/_index.md

---

wgs/cnai/onboarding/index.md

Change whitepaper hyperlink from `https://tag-runtime.cncf.io/whitepapers/cloudnativeai/` to `https://tag-runtime.cncf.io/wgs/cnaiwg/whitepapers/cloudnativeai/`

[Docs] Update index.md since the [white paper] url redirected to no page found

---

website/content/ja/wgs/COD/charter/index.md
wgs/cod/charter/index.md

This PR is a fix for minor issue highlighted in #160.
Fixes #160

fix GitHub url typo breaking profile urls

---

README.md

Following up from https://github.com/cncf/toc/pull/1349 to update TOC liaisons for TAG Runtime

Update TOC liaisons for TAG Runtime

---

wgs/wasm/deliverables/wasm-oci-artifact/index.md

As far as I know this is the current list of projects that have implemented the wasm OCI artifact layout. Let me know if I missed anything big, but it also isn't hard to catch in a follow up PR as well

feat(wasm): Updates OCI artifact deliverable with implementors

---

wgs/wasm/deliverables/wasm-oci-artifact/index.md

Spin already implements pulling "manifest-less apps" from OCI artifacts and will soon support pulling component dependencies as well.

feat(wasm): Update OCI artifact implementors

---

website/content/en/wgs/bsi/landscape
website/layouts/shortcodes/bsi-landscape-embed-view.html
wgs/bsi/charter/index.md
wgs/bsi/landscape/index.md

This PR sets up the BSI landscape page, embedding the full landscape from https://bsi-landscape.netlify.app/ (source: https://github.com/naskio/bsi-landscape)
- Added `weight` FrontMatter header to the BSI charter page for sorting.
- Added shortcode for embedding the BSI landscape.
- Created a dedicated BSI landscape page (en only).
- Resized the landscape iframe for optimal display.

Add BSI landscape embed view to BSI page

---

website/content/en/_index.md
website/content/ja/_index.md

Fixes #195 
---
This fixes the broken link in the website landing page for the mailing lists: I found the correct mailing list link in this repo's `README.md`
---
Before this change:
```
❯ rg https://lists.cncf.io/g/cncf-runtime/topics
website/content/en/_index.md
29:- [Mailing list](https://lists.cncf.io/g/cncf-runtime/topics)
website/content/ja/_index.md
28:- [メーリングリスト](https://lists.cncf.io/g/cncf-runtime/topics)
```
After this change:
```
❯ rg https://lists.cncf.io/g/cncf-runtime/topics
```

fix: Correct link for mailing list in landing page

---

website/content/en/wgs/bsi/_index.md

I wanted the initial page of the BSI working group to have a bit more info in it.  We can flesh it out more later, but at least this is a start.

Add 'Communications' and 'About' to the main page of the BSI WG

---

wgs/cnai/charter/index.md
wgs/cnai/onboarding/index.md

Fixing a few typos on the onboarding and charter pages for CNAI

Fix typos in CNAI website

---

website/content/en/_index.md

Looks like the TOC repo was reorganized just a little and the link to the TAG Runtime charter was broken.  Fixing that.

Fix the Runtime Charter link
